# Generated by Django 4.2.7 on 2025-09-02 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_supportticket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('details', models.TextField()),
                ('terms', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_combined', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='merchant_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='can_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='current_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks_reset_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('combined', 'Combined')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_level',
            field=models.CharField(choices=[('VIP 0', 'VIP 0'), ('VIP 1', 'VIP 1'), ('VIP 2', 'VIP 2'), ('VIP 3', 'VIP 3'), ('VIP 4', 'VIP 4')], default='VIP 0', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(default='usdt', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user', 'set_number', 'task_number')},
        ),
        migrations.AddField(
            model_name='task',
            name='products',
            field=models.ManyToManyField(related_name='tasks', to='accounts.product'),
        ),
    ]
