# Generated by Django 5.2.5 on 2025-09-06 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_campaign_product_invitation_referee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={},
        ),
        migrations.AlterModelOptions(
            name='termsandconditions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(default='usdt', max_length=50),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='wallet_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='referee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='assets',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='campaign',
            table='accounts_campaign',
        ),
        migrations.AlterModelTable(
            name='deposit',
            table='accounts_deposit',
        ),
        migrations.AlterModelTable(
            name='invitation',
            table='accounts_invitation',
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='accounts_portfolio',
        ),
        migrations.AlterModelTable(
            name='product',
            table='accounts_product',
        ),
        migrations.AlterModelTable(
            name='supportticket',
            table='accounts_supportticket',
        ),
        migrations.AlterModelTable(
            name='task',
            table='accounts_task',
        ),
        migrations.AlterModelTable(
            name='termsandconditions',
            table='accounts_terms',
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='accounts_userprofile',
        ),
        migrations.AlterModelTable(
            name='withdrawal',
            table='accounts_withdrawal',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='referee',
        ),
    ]
