# Generated by Django 4.2.7 on 2025-09-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_null_to_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_set',
        ),
    ]
